# Generated by Django 2.0.6 on 2018-06-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0002_corpus_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpus',
            name='binary_sentiment',
            field=models.CharField(default=False, max_length=5),
            preserve_default=False,
        ),
    ]
