# Generated by Django 2.0.6 on 2018-06-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0004_auto_20180606_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpus',
            name='TextBlob_sentiment_polarity',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='corpus',
            name='TextBlob_sentiment_subjectivity',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='corpus',
            name='binary_confidence',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='corpus',
            name='vaderSentiment_compound',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='corpus',
            name='vaderSentiment_neg',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='corpus',
            name='vaderSentiment_neu',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='corpus',
            name='vaderSentiment_pos',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
