# Generated by Django 2.0.6 on 2018-06-08 21:06

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classifier', '0005_auto_20180606_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('pos', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('binary_sentiment', models.CharField(blank=True, max_length=5, null=True)),
                ('binary_confidence', models.CharField(blank=True, max_length=5, null=True)),
                ('TextBlob_sentiment_polarity', models.CharField(blank=True, max_length=5, null=True)),
                ('TextBlob_sentiment_subjectivity', models.CharField(blank=True, max_length=5, null=True)),
                ('vaderSentiment_neg', models.CharField(blank=True, max_length=5, null=True)),
                ('vaderSentiment_neu', models.CharField(blank=True, max_length=5, null=True)),
                ('vaderSentiment_pos', models.CharField(blank=True, max_length=5, null=True)),
                ('vaderSentiment_compound', models.CharField(blank=True, max_length=5, null=True)),
                ('raw_tweet', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Corpus',
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='Corpus',
            new_name='UserText',
        ),
    ]
