# Generated by Django 2.0.6 on 2018-06-12 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0009_auto_20180611_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='text',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classifier.UserText'),
            preserve_default=False,
        ),
    ]
