# Generated by Django 2.0.6 on 2018-06-12 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0011_auto_20180611_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='text',
            new_name='texts',
        ),
    ]
