# Generated by Django 2.0.6 on 2018-06-13 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classifier', '0012_auto_20180611_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='texts',
            field=models.ManyToManyField(default=None, to='classifier.UserText'),
        ),
        migrations.RemoveField(
            model_name='topic',
            name='user',
        ),
        migrations.AddField(
            model_name='topic',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
